# Use Plotly or Bokeh to create beatiful and interactive maps with basemaps from Google or Mapbox
# Apart from the traditonal publication style static maps generated by shapefiles.







import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(figsize=(15,7.5))
ax = plt.axes()

x = np.linspace(0, 10, 1000)
ax.plot(x, np.sin(x))



# basic version
import mpld3

html_str = mpld3.fig_to_html(fig)
Html_file= open("sample.html","w")
Html_file.write(html_str)
Html_file.close()

# edit style
import mpld3
html_fragment = mpld3.fig_to_html(fig, figid = 'fig1')

html_doc = f'''
<style type="text/css">
div#fig1 {{ text-align: center }}
</style>

{html_fragment}
'''

Html_file= open("sample.html","w")
Html_file.write(html_doc)
Html_file.close()
